CREATE TABLE Clientes (
    cliente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100),
    telefono VARCHAR2(15),
    direccion VARCHAR2(255)
);
CREATE TABLE Coches (
    coche_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca VARCHAR2(50),
    modelo VARCHAR2(50),
    anio NUMBER,
    disponible CHAR(1) CHECK (disponible IN ('Y', 'N'))
);
CREATE TABLE Reservas (
    reserva_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER,
    coche_id NUMBER,
    fecha_reserva DATE,
    fecha_devolucion DATE,
    CONSTRAINT fk_cliente FOREIGN KEY (cliente_id) REFERENCES Clientes(cliente_id),
    CONSTRAINT fk_coche FOREIGN KEY (coche_id) REFERENCES Coches(coche_id)
);
CREATE TABLE Repuestos (
    repuesto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    cantidad NUMBER,
    precio NUMBER(10, 2)
);

INSERT INTO Clientes (nombre, email, telefono, direccion) VALUES
('Juan Pérez', 'juan@example.com', '123456789', 'Calle Falsa 123');

INSERT INTO Clientes (nombre, email, telefono, direccion) VALUES
('María López', 'maria@example.com', '987654321', 'Avenida Siempre Viva 456');


DESCRIBE Coches;
ALTER TABLE Coches
ADD (kilometraje NUMBER);

DESCRIBE Coches;

SELECT constraint_name, search_condition 
FROM user_constraints 
WHERE table_name = 'COCHES' AND constraint_type = 'C';

INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE)
VALUES (1, 'Focus', 'Ford', 2018, 'Y', 45000);

SELECT * FROM Coches;

INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (11, 'Fiesta', 'Ford', 2020, 'Y', 20000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (12, 'S-Class', 'Mercedes', 2021, 'Y', 15000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (13, 'Mustang', 'Ford', 2022, 'Y', 5000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (14, 'Q7', 'Audi', 2019, 'Y', 40000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (15, 'i8', 'BMW', 2021, 'Y', 10000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (16, 'Cayenne', 'Porsche', 2021, 'Y', 12000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (17, 'Challenger', 'Dodge', 2020, 'Y', 22000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (18, 'A6', 'Audi', 2018, 'Y', 45000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (19, 'X6', 'BMW', 2020, 'Y', 30000);
INSERT INTO Coches (COCHE_ID, MODELO, MARCA, ANIO, DISPONIBLE, KILOMETRAJE) VALUES (20, 'Aston Martin DB11', 'Aston Martin', 2021, 'Y', 8000);

SELECT * FROM Coches WHERE DISPONIBLE = 'Y';

SELECT * FROM Coches WHERE MARCA = 'Ford';

CREATE INDEX idx_marca ON Coches(MARCA);

CREATE VIEW coches_disponibles AS
SELECT * FROM Coches WHERE DISPONIBLE = 'Y';

SELECT * FROM coches_disponibles;









